name: Action test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: |
          npm run lint
          npm run compile
          npm run clean
          npm run build

      - name: Generate coverage json-summary files for action test
        run: |
          npm run test:base
          cp coverage/coverage-summary.json coverage/coverage-summary-base.json
          npm run test:head
        env:
          CI: true

      - name: Test action.yaml (No changes)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary-base.json
          head-summary-json: coverage/coverage-summary-base.json

      - name: Test action.yaml (Header and Footer)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary-base.json
          head-summary-json: coverage/coverage-summary-base.json
          body-header: |
            ## Hi
          body-footer: |
            ---
            [Link to GitHub](https://github.com)

      - name: Test action.yaml (Increase with default)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary-base.json
          head-summary-json: coverage/coverage-summary.json
          body-header: |
            ### Default coverage-diff options

      - name: Test action.yaml (Increase with custom config)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary-base.json
          head-summary-json: coverage/coverage-summary.json
          body-header: |
            ### Custom coverage-diff options
          check-criteria: lines
          coverage-threshold: 80

      - name: Test action.yaml (ENOTENT)
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-summary-json: coverage/coverage-summary-base.json
          head-summary-json: coverage/not-existing-coverage-summary.json
          body-header: |
            ### Custom coverage-diff options
          check-criteria: lines
          coverage-threshold: 80
